from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from api import generate_full_report
from pydantic import BaseModel
import uvicorn

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


class RequestModel(BaseModel):
    """
    Request model containing the company name for analysis.

    Attributes:
        company (str): Name of the company to analyze.
    """
    company: str


@app.post("/analyze/")
async def analyze_company(data: RequestModel):
    """
    Endpoint to trigger analysis for a given company.

    Parameters:
        data (RequestModel): JSON input containing the company name.

    Returns:
        dict: Complete sentiment report generated by the backend.
    """
    return generate_full_report(data.company)


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
